M48
; DRILL file {KiCad 9.0.7} date 2026-04-14T21:15:20+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-14T21:15:20+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.375
%
G90
G05
T1
X6.125Y24.82
X6.125Y19.04
T2
X19.964Y19.525
X20.98Y24.605
X21.996Y19.525
T3
X18.44Y24.605
X18.44Y21.43
X23.52Y24.605
X23.52Y21.43
M30
